### ISSUE TITLE
DLX execution not working

### ISSUE THREAD

**Issue by Hu1buerger** [huesersohn/dlx#10]
# Reproduce:

DLX-ASM 

``` asm
start:      ADDI    R1, R0, #1000
            ADD     R3, R0, R0
loop:       LW      R2, 0(R1)
            ADD     R3, R3, R2
            ADDI    R1, R1, #4
            SEQI    R4, R1, #1020
            BEQZ    R4, loop
            SW      0(R1), R3
            TRAP    #0
```
Tried on Safari 14.0.2, Firefox 84.0.2 (64 bit), and Chrome

# Fail 
fail at line 3 
on all browsers 

# Expected

execution to TRAP

**Comment by emcruise** [comment]
Same Issue here, using Firefox on Linux currently.

**Comment by 0MrX0** [comment]
I can not reproduce your issue.
Your code requires values at the addresses 1000 to 1020.
Is it possible that you forgot to put values there?

**Comment by Hu1buerger** [comment]
I assumed, because I have pressed RESET, that the memory cells are reset to 0 too. I would suggest that this behaviour should be implemented as it is the default in the industrie (i.e. 8051 reset triggered sets the memory cells to default values = 0) and it is expected in this context.

Otherwise it should be documented in the README

**Comment by huesersohn** [comment]
I'll take a look at this on the weekend and see what I can come up with. Maybe I should also add a help popup that details some things. Hovering over the line number of a line highlighted in red or yellow shows some hints as to what might be the problem.

**Comment by Hu1buerger** [comment]
sure I have seen that popup. maybe that is to ambiguous in this case but I wouldn't add another popup as it would crowd the GUI too much.
I would rather like an extensive documentation (instruction set, differences in implementation i.e. branch on x , immediate) and a link to it. I believe this would be the best way forward in the context of this project

**Comment by huesersohn** [comment]
I propose to read empty memory as 0 and maybe add a warning about that, I'll see what I can do and when I have time to implement it.

The reset button is only concerned about the execution state of the program, I don't want to touch that. What's more is that maybe you wouldn't always want to reset your custom memory.

@Hu1buerger regarding the documentation: this project started 10 years ago when I wanted to have a way to check my homework and uses the specific instruction set from that module. I don't really intend to develop this any further nor do I have time to write said documentation. But if you want to, go ahead and create a pull request. I will then consider merging it.

**Comment by huesersohn** [comment]
With be60ba6 memory will now be initialised with all 0s.
