### ISSUE TITLE
DLX Interpreter not working

### ISSUE THREAD

**Issue by axel0X1A4** [huesersohn/dlx#11]
The DLX interpreter at https://huesersohn.github.io/dlx/ doesn´t seem to be working. I tried some code of my own and then the examples, both failed without exception. Code I tested were the provided examples and :
start:      LW      R1, 1000(R0)
            ADD     R2, R0, R0
loop:       BEQZ    R1, ende
            ADD     R2, R2, R1
            SUBI    R1, R1, #1
            J       loop
ende:       SW      1004(R0), R2
            TRAP    #0

**Comment by huesersohn** [comment]
This seems to be the same problem as in #10, see there.
