### ISSUE TITLE
Creating a CodeMirror mode and styles package for DLX Assembly langauge

### ISSUE THREAD

**Issue by franciscohanna92** [huesersohn/dlx#9]
Hi! Nice project.

Would you mind if I isolate the mode and style files for CodeMirror into it's own npm package? 
I would find it useful for a project I working on. Of course, I will give you credits on the project README.

**Comment by huesersohn** [comment]
Sure, go for it :)

**Comment by franciscohanna92** [comment]
Great!

Here it is:
https://www.npmjs.com/package/codemirror-dlx
